name: 功能建议
description: 提交功能需求或改进建议
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        请说明你希望增加/改进的功能。为了更快评估，请尽量写清楚使用场景与期望结果。

        交流与讨论：
        - Telegram 频道：https://t.me/msmwiki
        - Telegram 交流群：https://t.me/msm_home
  - type: input
    id: version
    attributes:
      label: 当前使用版本
      description: 便于判断是否已有实现/是否需要升级
      placeholder: vX.Y.Z
    validations:
      required: true
  - type: dropdown
    id: install
    attributes:
      label: 部署方式
      options:
        - Docker / docker-compose
        - 单二进制（后端内置前端）
        - 前后端分离部署
        - 其他
    validations:
      required: true
  - type: checkboxes
    id: scope
    attributes:
      label: 涉及模块（可多选）
      options:
        - label: 后端（API/服务管理）
        - label: 前端（页面/交互）
        - label: MosDNS
        - label: SingBox
        - label: Mihomo
        - label: 文档/教程
        - label: 其他
  - type: textarea
    id: background
    attributes:
      label: 背景与痛点
      description: 你为什么需要这个功能？当前有什么不方便？
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: 需求描述
      description: 你希望怎么做？（交互、配置项、默认行为等）
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: 验收标准（可选）
      description: 用几条可验证的标准描述“做完是什么样”
      placeholder: |
        - ...
        - ...
    validations:
      required: false
  - type: textarea
    id: references
    attributes:
      label: 参考资料（可选）
      description: 相关链接、截图、同类开源项目实现方式等
    validations:
      required: false
